spring.application.name=manga-backend

# =========================================================
# 1. CONEXÃO COM O BANCO DE DADOS (PostgreSQL do Supabase)
# =========================================================
# Substitua 'SEU_PROJECT_REF' pelo código do seu projeto (ex: abcdefghijklm)
spring.datasource.url=postgresql://postgres:@1234We..#*&@db.vpszeztuyysrkhahmqnc.supabase.co:5432/postgres
spring.datasource.username=postgres

# Coloque a senha que você criou ao configurar o banco no Supabase
spring.datasource.password=@1234We..#*&

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuração de Conexões
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# =========================================================
# 2. PERMISSÃO DE TAMANHO DE ARQUIVO (.CBZ)
# =========================================================
# Permite o envio de arquivos e capas pesados de até 150MB
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

# =========================================================
# 3. CREDENCIAIS DO SUPABASE STORAGE (Para guardar os arquivos)
# =========================================================
# URL do seu projeto (ex: https://abcdefghijklm.supabase.co)
supabase.url=https://vpszeztuyysrkhahmqnc.supabase.co

# Cole aqui a chave 'service_role' (secret) que você pegou em API Keys
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwc3plenR1eXlzcmtoYWhtcW5jIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTkyNTA0MCwiZXhwIjoyMTA1NTAxMDQwfQ.g0LGiBygZ8TDns1_b3WjDn0_Yn_uzzzj5nYFh-62Eyo

# Nome do Bucket que você criou no menu Storage do Supabase
supabase.bucket=character
